# Generated by Django 5.0.4 on 2024-04-17 17:35

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.BigIntegerField(verbose_name='Телеграмм ID')),
                ('nickname', models.CharField(max_length=64, verbose_name='Никнейм')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Покупатель',
                'verbose_name_plural': 'Покупатели',
                'ordering': ('is_active',),
                'indexes': [models.Index(fields=['tg_id', 'is_active'], name='orders_buye_tg_id_1ff44a_idx'), models.Index(fields=['is_active'], name='orders_buye_is_acti_b9eaca_idx')],
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True, verbose_name='Цена товара')),
                ('status', models.CharField(choices=[('PE', 'В ожидании'), ('IP', 'В работе'), ('CO', 'Выполнен'), ('CA', 'Отменен')], default='PE', max_length=2, verbose_name='Статус')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='orders.buyer', verbose_name='Покупатель')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['created'], name='orders_orde_created_51311f_idx'), models.Index(fields=['buyer'], name='orders_orde_buyer_i_90aa29_idx')],
            },
        ),
    ]
