# Generated by Django 5.0.4 on 2024-04-18 07:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='id',
        ),
        migrations.AlterField(
            model_name='buyer',
            name='tg_id',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Телеграмм ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
