# Generated by Django 5.0.4 on 2024-04-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_buyer_id_alter_buyer_tg_id_alter_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Цена товара'),
        ),
    ]
