# Generated by Django 5.0.4 on 2024-05-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_remove_order_comment_alter_order_status_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PE', 'В ожидании'), ('IP', 'Ждем ответ'), ('BA', 'На согласовании'), ('PA', 'Оплачено'), ('CO', 'Выполнен'), ('CA', 'Отменен')], default='PE', max_length=2, verbose_name='Статус'),
        ),
    ]
