# Generated by Django 5.0.4 on 2024-05-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='link',
            field=models.URLField(max_length=1000, verbose_name='Ссылка'),
        ),
    ]
